Clinica-V3.0/Clinica-V3.0/Controllers/ConsultasController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Clinica_V3._0.Models;
using System.Data.Entity.Core.Objects;
using Microsoft.AspNet.Identity;

namespace Clinica_V3._0.Controllers
{

    public class ConsultasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Consultas
        public ActionResult Index(string stringPaciente, string stringMedico, string stringPlanoSaude)
        {
            var consultas = db.Consultas.Where(x => x.Comparecimento == false).Include(c => c.Paciente);
            var user = db.Users.Find(User.Identity.GetUserId());
            if (User.IsInRole("Medico"))
            {
                consultas = consultas.Where(s => s.Medico.Nome.Contains(user.Medico.Nome));
            }

                if (!String.IsNullOrEmpty(stringPaciente))
            {
                consultas = consultas.Where(s => s.Paciente.Nome.Contains(stringPaciente));
            }

            if (!String.IsNullOrEmpty(stringMedico))
            {
                consultas = consultas.Where(s => s.Medico.Nome.Contains(stringMedico));
            }

            if (!String.IsNullOrEmpty(stringPlanoSaude))
            {
                consultas = consultas.Where(s => s.PlanoDeSaude.Contains(stringPlanoSaude));
            }

            return View(consultas.ToList());
        }
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Consultas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consultas.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            return View(consulta);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // GET: Consultas/Create
        public ActionResult Create()
        {
            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome");
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome");
            return View();
        }

        // POST: Consultas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDConsulta,PlanoDeSaude,DataConsulta,IDPaciente,IDMedico")] Consulta consulta, string hora)
        {

            if (consulta.DataConsulta.Date < DateTime.Now.Date) {
                ModelState.AddModelError("DataConsulta", "A data da consulta deve ser maior ou igual a Hoje.");
            }

            if (hora == "")
            {
                ModelState.AddModelError("hora", "Insira uma hora válida.");
            }
            else
            {
                string[] array = hora.Split(':');
                DateTime novaData = new DateTime(consulta.DataConsulta.Year, consulta.DataConsulta.Month, consulta.DataConsulta.Day, int.Parse(array[0]), int.Parse(array[1]), 00);
                consulta.DataConsulta = novaData;
                var nomeMedico = db.Medico.Find(consulta.IDMedico).Nome;
                var consultaNoMesmoHorario = this.consultaMesmoHorario(novaData, nomeMedico);
                if (consultaNoMesmoHorario)
                {
                    ModelState.AddModelError("DataConsulta", "Já existe consulta neste mesmo Horário.");
                }
            }

            if (ModelState.IsValid)
            {
                db.Consultas.Add(consulta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome", consulta.IDPaciente);
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome", consulta.IDMedico);
            return View(consulta);
        }


        private bool consultaMesmoHorario(DateTime novaData, string nomeMedico)
        {
            foreach (Consulta cons in db.Consultas)
            {
                if (novaData >= cons.DataConsulta &&
                    novaData <= cons.DataConsulta.AddMinutes(30)
                    && cons.Medico.Nome.Equals(nomeMedico))
                {
                    return true;
                }
            }
            
            return false;

        }
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Consultas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consultas.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome", consulta.IDPaciente);
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome", consulta.IDMedico);
            return View(consulta);
        }
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // POST: Consultas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDConsulta,PlanoDeSaude,DataConsulta,IDPaciente,IDMedico,Comparecimento,Observacoes")] Consulta consulta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(consulta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome", consulta.IDPaciente);
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome", consulta.IDMedico);
            return View(consulta);
        }

        // GET: Consultas/Delete/5
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consultas.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            return View(consulta);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // POST: Consultas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consulta consulta = db.Consultas.Find(id);
            db.Consultas.Remove(consulta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult PacienteFilter(string term)
        {
            term = term.ToLower();
            var list = db.Consultas.Where(x => x.Paciente.Nome.ToLower().Contains(term)).Select(x => x.Paciente.Nome).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MedicoFilter(string term)
        {
            term = term.ToLower();
            var list = db.Consultas.Where(x => x.Medico.Nome.ToLower().Contains(term)).Select(x => x.Medico.Nome).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PlanoSaudeFilter(string term)
        {
            term = term.ToLower();
            var list = db.Consultas.Where(x => x.PlanoDeSaude.ToLower().Contains(term)).Select(x => x.PlanoDeSaude).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

Clinica-V3.0/Clinica-V3.0/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinica_V3._0.Models;

namespace Clinica_V3._0.Controllers
{
    [CustomAuthorize(Roles = "Administrador,Secretaria")]
    public class MedicosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Medicos
        public ActionResult Index(string stringNome, string stringEspecializacao)
        {
            var medicos = db.Medico.ToList();

            if (!String.IsNullOrEmpty(stringEspecializacao))
            {
                medicos = medicos.Where(s => s.Especilizacao.Contains(stringEspecializacao)).ToList();
            }

            if (!String.IsNullOrEmpty(stringNome))
            {
                medicos = medicos.Where(s => s.Nome.Contains(stringNome)).ToList();
            }
            return View(medicos);
        }

        // GET: Medicos/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medico medico = db.Medico.Find(id);
            if (medico == null)
            {
                return HttpNotFound();
            }
            return View(medico);
        }

        // GET: Medicos/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medico medico = db.Medico.Find(id);
            if (medico == null)
            {
                return HttpNotFound();
            }
           
            return View(medico);
        }

        // POST: Medicos/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Nome,Rg,Telefone,Endereco,Especilizacao")] Medico medico)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(medico);
        }

        // GET: Medicos/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medico medico = db.Medico.Find(id);
            if (medico == null)
            {
                return HttpNotFound();
            }
            return View(medico);
        }

        // POST: Medicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Medico medico = db.Medico.Find(id);
            ApplicationUser user = db.Users.Find(medico.UserId);
            db.Users.Remove(user);
            db.Medico.Remove(medico);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult NomeFilter(string term)
        {
            term = term.ToLower();
            var list = db.Medico.Where(x => x.Nome.ToLower().Contains(term)).Select(x => x.Nome).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EspecializacaoFilter(string term)
        {
            term = term.ToLower();
            var list = db.Medico.Where(x => x.Especilizacao.ToLower().Contains(term)).Select(x => x.Especilizacao).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

Clinica-V3.0/Clinica-V3.0/Controllers/SecretariasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinica_V3._0.Models;

namespace Clinica_V3._0.Controllers
{
    [CustomAuthorize(Roles = "Administrador,Secretaria")]
    public class SecretariasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Secretarias
        public ActionResult Index(string stringNome)
        {
            var secretarias = db.Secretaria.ToList();
            if (!String.IsNullOrEmpty(stringNome))
            {
                secretarias = secretarias.Where(s => s.Nome.Contains(stringNome)).ToList();
            }

            return View(secretarias);
        }

        // GET: Secretarias/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Secretaria secretaria = db.Secretaria.Find(id);
            if (secretaria == null)
            {
                return HttpNotFound();
            }
            return View(secretaria);
        }

        // GET: Secretarias/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Secretaria secretaria = db.Secretaria.Find(id);
            if (secretaria == null)
            {
                return HttpNotFound();
            }
            return View(secretaria);
        }

        // POST: Secretarias/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Nome,Rg,Telefone,Endereco")] Secretaria secretaria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(secretaria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(secretaria);
        }

        // GET: Secretarias/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Secretaria secretaria = db.Secretaria.Find(id);
            if (secretaria == null)
            {
                return HttpNotFound();
            }
            return View(secretaria);
        }

        // POST: Secretarias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Secretaria secretaria = db.Secretaria.Find(id);
            ApplicationUser user = db.Users.Find(secretaria.UserId);
            db.Users.Remove(user);
            db.Secretaria.Remove(secretaria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult NomeFilter(string term)
        {
            term = term.ToLower();
            var list = db.Secretaria.Where(x => x.Nome.ToLower().Contains(term)).Select(x => x.Nome).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

Clinica-V3.0/Clinica-V3.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Clinica CI</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/jqueryui")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Clinica CI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Administrador") || User.IsInRole("Secretaria"))
                    {
                        

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Usuários<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Criar Usuário", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                <li>@Html.ActionLink("Listar Secretárias", "Index", "Secretarias")</li>
                                <li>@Html.ActionLink("Listar Médicos", "Index", "Medicos")</li>
                                @if (User.IsInRole("Administrador"))
                                {
                                 <li>@Html.ActionLink("Listar Administradores", "Index", "Administradores")</li>
                                }
                            </ul>
                        </li>


                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pacientes <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Listar Pacientes", "Index", "Pacientes")</li>
                                <li>@Html.ActionLink("Novo Paciente", "Create", "Pacientes")</li>
                            </ul>
                        </li>
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Consultas <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Listar Consultas", "Index", "Consultas")</li>
                                <li>@Html.ActionLink("Novo Consulta", "Create", "Consultas")</li>
                            </ul>
                        </li>

                    }  @if (User.IsInRole("Medico"))
                    {
                        <li>@Html.ActionLink("Listar Pacientes", "Index", "Pacientes")</li>
                        <li>@Html.ActionLink("Listar Consultas", "Index", "Consultas")</li>

                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/ScriptsClinica/Mascaras.js")
    @Scripts.Render("~/bundles/inputmask");
    @RenderSection("scripts", required: false)
</body>
</html>