Clinica-V3.0/Clinica-V3.0/Models/Consulta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Clinica_V3._0.Models
{
    public class Consulta
    {
        [Key]
        public int IDConsulta { get; set; }
        [Required]
        [Display(Name = "Plano de saude")]
        public string PlanoDeSaude { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Data da Consulta")]
        public DateTime DataConsulta { get; set; }
        [Required]
        [DisplayName("Paciente")]
        public int IDPaciente { get; set; }
        public virtual Paciente Paciente { get; set; }
        [Required]
        [DisplayName("Médico")]
        [ForeignKey("Medico")]
        public string IDMedico { get; set; }
        public virtual Medico Medico { get; set; }
        public bool Comparecimento { get; set; }
        [DisplayName("Observações")]
        public string Observacoes { get; set; }
    }
}

Clinica-V3.0/Clinica-V3.0/Controllers/ConsultasController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Clinica_V3._0.Models;
using System.Data.Entity.Core.Objects;
using Microsoft.AspNet.Identity;

namespace Clinica_V3._0.Controllers
{

    public class ConsultasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Consultas
        public ActionResult Index(string stringPaciente, string stringMedico, string stringPlanoSaude)
        {
            var consultas = db.Consultas.Where(x => x.Comparecimento == false).Include(c => c.Paciente);
            var user = db.Users.Find(User.Identity.GetUserId());
            if (User.IsInRole("Medico"))
            {
                consultas = consultas.Where(s => s.Medico.Nome.Contains(user.Medico.Nome));
            }

                if (!String.IsNullOrEmpty(stringPaciente))
            {
                consultas = consultas.Where(s => s.Paciente.Nome.Contains(stringPaciente));
            }

            if (!String.IsNullOrEmpty(stringMedico))
            {
                consultas = consultas.Where(s => s.Medico.Nome.Contains(stringMedico));
            }

            if (!String.IsNullOrEmpty(stringPlanoSaude))
            {
                consultas = consultas.Where(s => s.PlanoDeSaude.Contains(stringPlanoSaude));
            }

            return View(consultas.ToList());
        }
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Consultas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consultas.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            return View(consulta);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // GET: Consultas/Create
        public ActionResult Create()
        {
            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome");
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome");
            return View();
        }

        // POST: Consultas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDConsulta,PlanoDeSaude,DataConsulta,IDPaciente,IDMedico")] Consulta consulta, string hora)
        {

            if (consulta.DataConsulta.Date < DateTime.Now.Date) {
                ModelState.AddModelError("DataConsulta", "A data da consulta deve ser maior ou igual a Hoje.");
            }

            if (hora == "")
            {
                ModelState.AddModelError("hora", "Insira uma hora válida.");
            }
            else
            {
                string[] array = hora.Split(':');
                DateTime novaData = new DateTime(consulta.DataConsulta.Year, consulta.DataConsulta.Month, consulta.DataConsulta.Day, int.Parse(array[0]), int.Parse(array[1]), 00);
                consulta.DataConsulta = novaData;
                var nomeMedico = db.Medico.Find(consulta.IDMedico).Nome;
                var consultaNoMesmoHorario = this.consultaMesmoHorario(novaData, nomeMedico);
                if (consultaNoMesmoHorario)
                {
                    ModelState.AddModelError("DataConsulta", "Já existe consulta neste mesmo Horário.");
                }
            }

            if (ModelState.IsValid)
            {
                db.Consultas.Add(consulta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome", consulta.IDPaciente);
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome", consulta.IDMedico);
            return View(consulta);
        }


        private bool consultaMesmoHorario(DateTime novaData, string nomeMedico)
        {
            foreach (Consulta cons in db.Consultas)
            {
                if (novaData >= cons.DataConsulta &&
                    novaData <= cons.DataConsulta.AddMinutes(30)
                    && cons.Medico.Nome.Equals(nomeMedico))
                {
                    return true;
                }
            }
            
            return false;

        }
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Consultas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consultas.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome", consulta.IDPaciente);
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome", consulta.IDMedico);
            return View(consulta);
        }
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // POST: Consultas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDConsulta,PlanoDeSaude,DataConsulta,IDPaciente,IDMedico,Comparecimento,Observacoes")] Consulta consulta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(consulta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDPaciente = new SelectList(db.Paciente, "IDPaciente", "Nome", consulta.IDPaciente);
            ViewBag.IDMedico = new SelectList(db.Medico, "UserId", "Nome", consulta.IDMedico);
            return View(consulta);
        }

        // GET: Consultas/Delete/5
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consultas.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            return View(consulta);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // POST: Consultas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consulta consulta = db.Consultas.Find(id);
            db.Consultas.Remove(consulta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult PacienteFilter(string term)
        {
            term = term.ToLower();
            var list = db.Consultas.Where(x => x.Paciente.Nome.ToLower().Contains(term)).Select(x => x.Paciente.Nome).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MedicoFilter(string term)
        {
            term = term.ToLower();
            var list = db.Consultas.Where(x => x.Medico.Nome.ToLower().Contains(term)).Select(x => x.Medico.Nome).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PlanoSaudeFilter(string term)
        {
            term = term.ToLower();
            var list = db.Consultas.Where(x => x.PlanoDeSaude.ToLower().Contains(term)).Select(x => x.PlanoDeSaude).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

Clinica-V3.0/Clinica-V3.0/Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinica_V3._0.Models;

namespace Clinica_V3._0.Controllers
{
    
    public class PacientesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Pacientes
        public ActionResult Index(string stringNome, string stringTelefone)
        {
            var pacientes = db.Paciente.ToList();
            if (!String.IsNullOrEmpty(stringNome))
            {
                pacientes = pacientes.Where(s => s.Nome.Contains(stringNome)).Select(x => x).ToList();
            }

            if (!String.IsNullOrEmpty(stringTelefone))
            {
                pacientes = pacientes.Where(s => s.Telefone.Contains(stringTelefone)).Select(x => x).ToList(); 
            }

            return View(pacientes);
        }
        [CustomAuthorize(Roles = "Medico,Administrador,Secretaria")]
        // GET: Pacientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // GET: Pacientes/Create
        public ActionResult Create()
        {
            return View();
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // POST: Pacientes/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDPaciente,Nome,Telefone")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.Paciente.Add(paciente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paciente);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // GET: Pacientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // POST: Pacientes/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDPaciente,Nome,Telefone,Endereco,DataNascimento")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paciente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paciente);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // GET: Pacientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }
        [CustomAuthorize(Roles = "Administrador,Secretaria")]
        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Paciente paciente = db.Paciente.Find(id);
            db.Paciente.Remove(paciente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult NomeFilter(string term)
        {
            term = term.ToLower();
            var list = db.Paciente.Where(x => x.Nome.ToLower().Contains(term)).Select(x => x.Nome).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult TelefoneFilter(string term)
        {
            term = term.ToLower();
            var list = db.Paciente.Where(x => x.Telefone.ToLower().Contains(term)).Select(x => x.Telefone).Distinct();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

Clinica-V3.0/Clinica-V3.0/Views/Consultas/Create.cshtml
@model Clinica_V3._0.Models.Consulta

@{
    ViewBag.Title = "Criar Consulta";
}

<h2>Criar Consulta</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PlanoDeSaude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlanoDeSaude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlanoDeSaude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataConsulta, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataConsulta, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.DataConsulta, "", new { @class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hora da consulta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("hora", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessage("hora","", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDPaciente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDPaciente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDPaciente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDMedico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDMedico", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMedico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista de Consultas", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica-V3.0/Clinica-V3.0/Views/Consultas/Delete.cshtml
@model Clinica_V3._0.Models.Consulta

@{
    ViewBag.Title = "Deletar Consulta";
}

<h2>Deletar Consulta</h2>

<h3>Você deseja mesmo deletar esta consulta?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Paciente.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paciente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlanoDeSaude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlanoDeSaude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataConsulta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataConsulta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDMedico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medico.Nome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para Lista de Consultas", "Index")
        </div>
    }
</div>

Clinica-V3.0/Clinica-V3.0/Views/Consultas/Details.cshtml
@model Clinica_V3._0.Models.Consulta

@{
    ViewBag.Title = "Detalhes da Consulta";
}

<h2>Detalhes da Consulta</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PlanoDeSaude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlanoDeSaude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataConsulta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataConsulta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDPaciente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paciente.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IDMedico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medico.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Observacoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacoes)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IDConsulta }) |
    @Html.ActionLink("Voltar para Lista de Consultas", "Index")
</p>

Clinica-V3.0/Clinica-V3.0/Views/Consultas/Edit.cshtml
@model Clinica_V3._0.Models.Consulta

@{
    ViewBag.Title = "Editar Consulta";
}

<h2>Editar Consulta</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDConsulta)

        <div class="form-group">
            @Html.LabelFor(model => model.PlanoDeSaude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlanoDeSaude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlanoDeSaude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataConsulta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataConsulta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataConsulta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDPaciente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDPaciente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDPaciente, "", new { @class = "text-danger" })
                @if (Model.Paciente.Endereco == null && Model.Paciente.DataNascimento == null)
                {
                   @Html.ActionLink("Finalizar Cadastro do Paciente?", "Edit", "Pacientes", new { id= Model.IDPaciente }, new { target = "_blank" })
                }
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.IDMedico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownList("IDMedico", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMedico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comparecimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Comparecimento, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        @if (User.IsInRole("Medico"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Observacoes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Observacoes, new { rows = 10, cols = 40 })
                </div>
            </div>
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista de Consultas", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Clinica-V3.0/Clinica-V3.0/Views/Consultas/Index.cshtml
@model IEnumerable<Clinica_V3._0.Models.Consulta>

@{
    ViewBag.Title = "Lista de Consultas";
}

<h2>Lista de Consultas</h2>
@if (!User.IsInRole("Medico"))
{
<p>
    @Html.ActionLink("Criar uma nova Consulta", "Create")
</p>
}
<h4>Buscar por:</h4>
@using (Html.BeginForm())
{
    <p>
        Paciente: @Html.TextBox("stringPaciente")
        Médico: @Html.TextBox("stringMedico")
        Plano de Saúde: @Html.TextBox("stringPlanoSaude")
        <input type="submit" value="Procurar" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataConsulta)
            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlanoDeSaude)
        </th>
        <th>
            @Html.DisplayName("Paciente")
        </th>
        <th>
            @Html.DisplayName("Médico")
        </th>
        <th>
            @Html.DisplayName("Comparecimento")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DataConsulta)
           
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlanoDeSaude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paciente.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Medico.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comparecimento)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.IDConsulta }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.IDConsulta }) 
            @if (!User.IsInRole("Medico"))
            { <span>|</span>
             @Html.ActionLink("Deletar", "Delete", new { id = item.IDConsulta })
            }
            
        </td>
    </tr>
}

</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/ScriptsClinica/Consulta.js")
}